language: python
python:
  - "3.6"
dist: bionic
services:
  - docker
before_install:
  - docker network create hive
  - docker run -d --name hive-mongo --network hive -v  ${PWD}/.mongodb-data:/data/db -p 27020:27017 mongo
  - docker run -d --name hive-test-mongo --network hive -v  ${PWD}/.mongodb-test-data:/data/db -p 27022:27017 mongo
#  - sudo mkdir /etc/hive && sudo cp payment_config.json /etc/hive/
  - cp .env.example .env
install:
  - pip install -r requirements.txt
script:
  - pytest --disable-pytest-warnings -xs tests_v1/hive_auth_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_mongo_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_file_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_scripting_test.py
#  - pytest --disable-pytest-warnings -xs tests_v1/hive_payment_test.py
#  - pytest --disable-pytest-warnings -xs tests_v1/hive_backup_test.py
#  - pytest --disable-pytest-warnings -xs tests_v1/hive_internal_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_pubsub_test.py
