language: python
python:
  - "3.9.12"
dist: bionic
services:
  - docker
before_install:
  - docker network create hive
  - docker run -d --name hive-mongo --network hive -v  ${PWD}/.mongodb-data:/data/db -p 27020:27017 mongo:4.4.0
  - mkdir -p ${PWD}/.ipfs-data/ipfs-docker-staging
  - mkdir -p ${PWD}/.ipfs-data/ipfs-docker-data
  - docker run -d --name ipfs-node -v ${PWD}/.ipfs-data/ipfs-docker-staging:/export -v ${PWD}/.ipfs-data/ipfs-docker-data:/data/ipfs -p 8080:8080 -p 4001:4001 -p 127.0.0.1:5020:5001 ipfs/go-ipfs:latest
  - cp config/.env.local .env
  - pip install -r requirements.txt
  - pip3 install pyOpenSSL --upgrade # fix error: module 'lib' has no attribute 'OpenSSL_add_all_algorithms' (pymongo)
install:
  - docker ps
script:
  - pytest --disable-pytest-warnings -xs tests_v1/hive_auth_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_subscription_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_mongo_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_file_test.py
  - pytest --disable-pytest-warnings -xs tests_v1/hive_scripting_test.py

  - TRAVIS=True python manage.py runserver &
  - ./wait_node.sh
  - pytest --disable-pytest-warnings -xs tests/about_test.py
  - pytest --disable-pytest-warnings -xs tests/auth_test.py
  - pytest --disable-pytest-warnings -xs tests/subscription_test.py
  - pytest --disable-pytest-warnings -xs tests/database_test.py
  - pytest --disable-pytest-warnings -xs tests/files_test.py
  - pytest --disable-pytest-warnings -xs tests/scripting_test.py
  - pytest --disable-pytest-warnings -xs tests/payment_test.py
  - pytest --disable-pytest-warnings -xs tests/backup_test.py
  - pytest --disable-pytest-warnings -xs tests/provider_test.py
