version: "3.3"

services:

  hive-mongo-1:
    image: mongo:4.4.0
    volumes:
      - ${PWD}/.mongodb-1-data:/data/db
    ports:
      - "27021:27017"
    restart: always

  hive-node-1:
    depends_on:
      - hive-mongo-1
    image: elastos/hive-node
    volumes:
      - ${PWD}/.data1:/src/data
      - ${PWD}/.env1:/src/.env
      - ${PWD}/payment_config.json:/src/payment_config.json
    ports:
      - "5002:5000"
      - "2121:2121"
    restart: always